# Part 1: Data Exploration with Pandas

Load the Dataset

In [1]:
import pandas as pd
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [10]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [11]:
df.tail(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16990      1530.0       653.0         1.7038             78300.0  
16991      1343.0       479.0         2.4805             73200.0  
16992       544.0       172.0         3.3462             50800.0  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

Data Summary

In [12]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [15]:
print(f'Unique values in total_bedrooms: {df.total_bedrooms.unique()}')
print(f'No. of unique values in total_bedrooms: {df.total_bedrooms.nunique()}')

Unique values in total_bedrooms: [1283. 1901.  174. ... 1637. 1308.  936.]
No. of unique values in total_bedrooms: 1848


Data Transformation

In [18]:
df['total_bedrooms_per_total_rooms'] = df['total_bedrooms'] / df['total_rooms']
mean = df['total_bedrooms_per_total_rooms'].mean()
std = df['total_bedrooms_per_total_rooms'].std()
print(f'Mean of total_bedrooms_per_total_rooms = {mean}')
print(f'Standard Deviation of total_bedrooms_per_total_rooms = {std}')

Mean of total_bedrooms_per_total_rooms = 0.21275998821034803
Standard Deviation of total_bedrooms_per_total_rooms = 0.057823008903161756


Data Filtering

In [19]:
df[df['median_income']>5]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  median_house_value  \
32          481.0       185.0         6.2558            146300.0   
69          952.0       360.0         5.4349            143000.0   
92          871.0       222.0         6.2715             97200.0   
98         1416.0       421.0         5.7843            110100.0   
100        1000.0       287.0         6.3814            159900.0   
...           ...         ...            ...                 ...   
16737       931.0       336.0         5.7664            267500.0   
16762       728.0       250.0         5.1005            266700.0   
16776       851.0       418.0         5.6445            364800.0   
16802      1030.0       308.0         5.9585            214900.0   
16899       516.0       181.0         5.0329            165600.0   

       total_bedrooms_per_total_rooms  
32                           0.172535  
69                           0.161077  
92                           0.153194  
98                           0.165998  
100                          0.140632  
...                               ...  
16737                        0.182945  
16762                        0.173856  
16776                        0.197642  
16802                        0.145982  
16899                        0.149449  

[3752 rows x 10 columns]

In [23]:
df[(df['total_rooms']>10000) & (df['median_house_value']<150000)]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  median_house_value  \
133        4507.0      1807.0         2.2466             66800.0   
191        2453.0      1232.0         1.7844             78500.0   
198        3811.0      1570.0         4.0079            134500.0   
201        4122.0      1653.0         2.7219             74400.0   
229        6274.0      2095.0         2.4497             90900.0   
...           ...         ...            ...                 ...   
12654      6837.0      2358.0         3.1250            132500.0   
12772     28566.0      6082.0         2.3087            118800.0   
13388      9879.0      2152.0         2.5681             81300.0   
13707      6657.0      1874.0         4.9222            142900.0   
15436      6511.0      2267.0         3.5522            100100.0   

       total_bedrooms_per_total_rooms  
133                          0.224631  
191                          0.246715  
198                          0.203194  
201                          0.203059  
229                          0.245522  
...                               ...  
12654                        0.217481  
12772                        0.197536  
13388                        0.204803  
13707                        0.160860  
15436                        0.167858  

[67 rows x 10 columns]

Export Modified Data

In [24]:
df.to_csv('/content/sample_data/modified_california_housing_train.csv', index=False)

#Part 2: Numerical Analysis with NumPy

Array Creation and Indexing

In [1]:
import numpy as np

In [10]:
arr1 = np.arange(1, 21)
arr2 = np.random.choice(range(10,101), size=(5,4))
print(arr1)
print(arr1[1::2])
print(arr2)
print(arr2[:3, :2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]
[[65 11 82 97]
 [31 58 28 48]
 [82 81 98 21]
 [40 11 23 95]
 [95 66 60 61]]
[[65 11]
 [31 58]
 [82 81]]


Array Manipulation

In [18]:
arr1 = arr1.reshape(4,5)
arr2 = arr2.flatten()
arr3 = np.random.randint(1, 21, size=(5,4))
print(arr2)
print(np.dot(arr1, arr3))

[65 11 82 97 31 58 28 48 82 81 98 21 40 11 23 95 95 66 60 61]
[[  71  272  186  192]
 [ 181  712  466  527]
 [ 291 1152  746  862]
 [ 401 1592 1026 1197]]


Boolean and Fancy Indexing

In [22]:
arr4 = np.random.randint(1, 101, size=(50))
idx = np.where(arr4>50)
print(arr4[idx])
print(arr4[[3,6,23,46,49]])

[80 78 56 99 68 79 99 93 56 59 96 94 96 79 71 51 91 93 51 56 85 69 93 65
 94 95 52 98 62 91]
[99 17 50 98 36]


Statistical Operations

In [28]:
print(arr1.mean(axis=0))
print(arr1.sum(axis=0))
print(arr1.max(axis=0))

[ 8.5  9.5 10.5 11.5 12.5]
[34 38 42 46 50]
[16 17 18 19 20]


In [36]:
mask = np.array([arr1[:,i]>arr1.mean(axis=0)[i] for i in range(5)]).T
print(arr1[mask])

[11 12 13 14 15 16 17 18 19 20]


#Part 3: Problem Solving with Python Basics

Loops and Conditional Statements

In [38]:
fib = [0, 1]
for i in range(2, 100):
  fib.append(fib[i-1] + fib[i-2])
print(fib)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961, 4052739537881, 6557470319842, 10610209857723, 17167680177565, 27777890035288, 44945570212853, 72723460248141, 117669030460994, 190392490709135, 308061521170129, 498454011879264, 806515533049393, 1304969544928657, 2111485077978050, 3416454622906707, 5527939700884757, 8944394323791464, 14472334024676221, 23416728348467685, 37889062373143906, 61305790721611591, 99194853094755497, 160500643816367088, 259695496911122585, 420196140727489673, 679891637638612258, 110008777

In [39]:
for i in range(1, 51):
  if i%3==0 and i%5==0:
    print(f'{i}: FizzBuzz')
  elif i%3==0:
    print(f'{i}: Fizz')
  elif i%5==0:
    print(f'{i}: Buzz')

3: Fizz
5: Buzz
6: Fizz
9: Fizz
10: Buzz
12: Fizz
15: FizzBuzz
18: Fizz
20: Buzz
21: Fizz
24: Fizz
25: Buzz
27: Fizz
30: FizzBuzz
33: Fizz
35: Buzz
36: Fizz
39: Fizz
40: Buzz
42: Fizz
45: FizzBuzz
48: Fizz
50: Buzz


Variable-Length Arguments

In [42]:
n1 = input('Enter <space> separated nos. (Eg: 2 3 34 45): ').split()
n1 = [int(i) for i in n1]
n1.sort()
if len(n1)%2==0:
  print(f'Median = {(n1[len(n1)//2] + n1[len(n1)//2 - 1]) / 2}')
else:
  print(f'Median = {n1[len(n1)//2]}')

Enter <space> separated nos. (Eg: 2 3 34 45): 2 3
Median = 2.5


In [43]:
n2 = input('Enter <space> separated nos. (Eg: 2 3 34 45): ').split()
n2 = [int(i) for i in n2]
print(f'Mean = {sum(n2) / len(n2)}')

Enter <space> separated nos. (Eg: 2 3 34 45): 2 3 4 5 2 3 2 3 3 3 4 44 4 3
Mean = 6.071428571428571


Error Handling

In [50]:
try:
  1/0
except ZeroDivisionError:
  print('Cannot divide by zero')

Cannot divide by zero


#Part 4: Bonus Challenge

Advanced NumPy Manipulation

In [51]:
arr5 = np.random.randint(1, 101, size=(3,4,5))
print(arr5)

[[[ 12  16  18   6  71]
  [ 21  84  70  13  98]
  [ 76  67  16  86  37]
  [ 30  11  35   4  46]]

 [[  9  53  68  50   8]
  [ 16  23  65  59  39]
  [ 89  29  33  92  24]
  [ 58  36  35  53  27]]

 [[100  86  65  76  89]
  [ 24  45  86  24  74]
  [ 30  62  63  58  28]
  [ 58   6  36  26  60]]]


In [52]:
arr5 = np.swapaxes(arr5, 0, 2)
print(arr5)

[[[ 12   9 100]
  [ 21  16  24]
  [ 76  89  30]
  [ 30  58  58]]

 [[ 16  53  86]
  [ 84  23  45]
  [ 67  29  62]
  [ 11  36   6]]

 [[ 18  68  65]
  [ 70  65  86]
  [ 16  33  63]
  [ 35  35  36]]

 [[  6  50  76]
  [ 13  59  24]
  [ 86  92  58]
  [  4  53  26]]

 [[ 71   8  89]
  [ 98  39  74]
  [ 37  24  28]
  [ 46  27  60]]]


In [56]:
print(arr5.sum(axis=0))

[[123 188 416]
 [286 202 253]
 [282 267 241]
 [126 209 186]]


In [59]:
arr6 = np.random.randint(1, 101, size=(3,4))
print(arr6)
arr6 += np.random.randint(10, size=(4))
print(arr6)

[[51 52 70 34]
 [27 24 46 35]
 [30  8 36 47]]
[[53 57 74 34]
 [29 29 50 35]
 [32 13 40 47]]
